add template
DigicaSolutions/frontend-react-template pull request #1
Opened 2023-04-07 10:46 UTC by michalparysz-digica

**Dyson Front-end React Template Project 1.0.0v.**

It's Dyson Front-end internal project template for React Applications with recommended packages, configurations and rules.
Following command was used to initially setup this project `pnpm create vite [insert-app-name] --template react-swc-ts`.
This command creates **Vite + React + Typescript + SWC** (Rust Based Compiler) template.
On top of that below libraries, tools and configurations were added with initial setup.

2023-04-07 11:52 UTC, pawelpreczynski-digica requested changes

2023-04-07 11:52 UTC, pawelpreczynski-digica commented on .husky/pre-commit
> +pnpm format
I do not like that. we should enforce checking on CI not on developer machine. We should enforce rules but not how developer is working. Using husky leads to developers waiting on commit. I have done this on save on my IDE. I don't need to wait for that when doing commit.

2023-04-07 11:52 UTC, pawelpreczynski-digica commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
YES!

2023-04-07 11:52 UTC, pawelpreczynski-digica commented on README.md
> +# Dyson Front-end React Template Project 1.0.0v.
```suggestion
# Digica Front-end React Template Project 1.0.0v.
```

2023-04-07 11:52 UTC, pawelpreczynski-digica commented on README.md
> +It's Dyson Front-end internal project template for React Applications with recommended packages, configurations and rules.
```suggestion
It's Digica Front-end internal project template for React Applications with recommended packages, configurations and rules.
```

2023-04-07 11:52 UTC, pawelpreczynski-digica commented on package.json
> +    "test:coverage": "vitest run --coverage",
The difference here is that one of this runs is for CI and the other is for TDD. 
For TDD we should `vitest --coverage`. Then tests are run in watch mode and produce coverage information needed for developer. 
For CI we need to run tests once with coverage directory generated `vitest run`
```suggestion
    "test": "vitest --coverage",
    "test:ci": "vitest run",
```

2023-04-07 12:21 UTC, michalparysz-digica commented on .husky/pre-commit
> +pnpm format
It's local setup and it's easy to turn off individually. We can add `.husky` directory to `.gitignore`. 

It performs format check which is really fast, as a benefit it prevents CI actions from starting and failing on some simple cases of having file wrongly formated or not following eslint rules. In addition there will be less wasting resources by launching github actions that for sure are going to fail.

We can discuss it on next front-end status meeting.

2023-04-07 12:22 UTC, michalparysz-digica commented on README.md
> +# Dyson Front-end React Template Project 1.0.0v.
done thank you :-)

2023-04-07 12:22 UTC, michalparysz-digica commented on README.md
> +It's Dyson Front-end internal project template for React Applications with recommended packages, configurations and rules.
done thank you :-)

2023-04-07 12:27 UTC, michalparysz-digica commented on .eslintrc.cjs
> +    "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
I am glad you like it :-) I run through the dyson typescript and eslint rules document, I think I didn't missed any.

2023-04-07 12:28 UTC, michalparysz-digica commented on package.json
> +    "test:coverage": "vitest run --coverage",
done thank you :-)

2023-04-07 12:42 UTC, pawelpreczynski-digica commented on .husky/pre-commit
> +pnpm format
Nice! didn't sow that.

2023-04-07 12:54 UTC, michalparysz-digica commented on .husky/pre-commit
> +pnpm format
Unfortunately it semms not possible to have husky configuration added to `.gitignore` in the project and delete it locally without having hanging changes visible. Because this `.husky` directory is already in the repository.

2023-04-07 13:56 UTC, pawelpreczynski-digica requested changes

2023-04-07 13:56 UTC, pawelpreczynski-digica commented on README.md
> +
please update test command description. `pnpm test` is duplicated.

2023-04-07 13:56 UTC, pawelpreczynski-digica commented on src/App.tsx
> +export default App;
Why we have this approach to define variable when not needed? I'm not saying it's wrong. I just don't understand it. 
```suggestion
export default function App(): JSX.Element {
  return (
    <div className="App">
      <h1>Dyson Front-end React Template Project</h1>
    </div>
  );
};
```
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

2023-04-07 14:10 UTC, michalparysz-digica commented on src/App.tsx
> +export default App;
It comes from React & Typescript Cheat Sheet Recommended Practices.
https://github.com/typescript-cheatsheets/react/blob/main/README.md#function-components

2023-04-07 14:10 UTC, michalparysz-digica commented on README.md
> +
done thank you

2023-04-11 07:34 UTC, jakubpawelec-digica commented on package.json
> +    "@emotion/styled": "^11.10.6",
emotion/react &&  emotion/styled should not be in devDependecies

2023-04-11 07:34 UTC, jakubpawelec-digica commented on tsconfig.json
> +    "verbatimModuleSyntax": true,
I love it, but with new typescript rule we need to provide this https://typescript-eslint.io/rules/no-import-type-side-effects to avoid bugs

2023-04-11 07:34 UTC, jakubpawelec-digica commented on vite.config.ts
> +  server: {
We don't need port 3000, it's set because our Dyson had cors to work only with 3000

2023-04-11 09:23 UTC, michalparysz-digica commented on package.json
> +    "@emotion/styled": "^11.10.6",
thank you :-)

2023-04-11 09:28 UTC, michalparysz-digica commented on tsconfig.json
> +    "verbatimModuleSyntax": true,
done thank you :-)

2023-04-11 09:31 UTC, michalparysz-digica commented on vite.config.ts
> +  server: {
I think it can stay as default port, 3000 port is known for being one of the default ones in the industry. Individual teams using this template can change it if they feel a need to do it or there is collision with some different applications.

2023-04-11 10:17 UTC, nijatsadikhov-digica approved these changes
Looks clean 👍

2023-04-11 10:26 UTC, muslimbekabduvaliev-digica approved these changes
Looks good

2023-04-11 11:40 UTC, jakubpawelec-digica approved these changes

2023-04-11 12:02 UTC, pawelpreczynski-digica approved these changes
Good job!

2023-04-11 12:13 UTC, merged